---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: fedora32
    - MOLECULE_DISTRO: fedora31
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: fedora28
    - MOLECULE_DISTRO: fedora27
    - MOLECULE_DISTRO: amazonlinux2

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-timesyncd sgaduuw.timesyncd
  - cd sgaduuw.timesyncd

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
